[package]
name = "e-waste-blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
sha2 = "0.10.6"
hex = "0.4.3"
p256 = "0.12.0"
rand_core = "0.6.4"